#!/usr/bin/env python3
# GENERATED by contract/gen.py from contract/spec.toml — DO NOT EDIT. Run `make gen`.
import re

DEFAULT_GARDEN = "default"
ID_MIN_LEN = 1
ID_MAX_LEN = 64
_ID_RE = re.compile(r"[a-z0-9-]{1,64}")

TOKEN_SLOT_CURRENT = "token_current"
TOKEN_SLOT_PREVIOUS = "token_previous"

HEADER_GARDEN_ID = "X-Garden-Id"
HEADER_DEVICE_ID = "X-Device-Id"
HEADER_NODE_ID = "X-Node-Id"
HEADER_TRACE_ID = "X-Garden-Trace-Id"
HEADER_AUTH = "X-Garden-Auth"
HEADER_CAPTURE_TS = "X-Capture-Ts"
HEADER_CAPTURE_BATCH = "X-Capture-Batch"
HEADER_TRIGGER = "X-Trigger"

NODE_OFFLINE_AFTER_SECS = 150
RAIN_TELEMETRY_FRESH_SECS = 600
MITIGATE_THRESHOLD = 0.3
SECONDS_PER_DAY = 86400

CONTROL_COMMANDS = ["off", "monitor", "active", "stop", "resume", "arm", "disarm"]

ASSET_VERSION = "31"

# The shared nav model (id, href, label, viewer_ok, group), rendered server-side by
# render_nav() so the edge (view-only) and Pi (admin) tiers can never drift.
NAV = [
    ("dashboard", "/", "Dashboard", True, ""),
    ("history", "/history", "History", True, ""),
    ("timelapse", "/timelapse", "Timelapse", True, ""),
    ("alarms", "/alarms", "Alarms", True, ""),
    ("devices", "/devices", "Gadgets", False, "admin"),
    ("settings", "/settings", "Settings", False, "admin"),
    ("costs", "/costs", "Costs", False, "admin"),
    ("logs", "/logs", "Logs", False, "admin"),
    ("storage", "/storage", "Storage", False, "admin"),
    ("help", "/help", "Help", True, ""),
]


def is_valid_id(s):
    """True iff `s` is a valid tenancy id (charset a-z0-9-, len 1..64)."""
    return isinstance(s, str) and _ID_RE.fullmatch(s) is not None


def key(gid, name):
    """garden_state KV key for a garden-level flag (default -> legacy flat key)."""
    return name if gid == DEFAULT_GARDEN else f"g/{gid}/{name}"


def dev_key(gid, did, name):
    """garden_state KV key for a per-device value (default -> legacy global key)."""
    return name if gid == DEFAULT_GARDEN else f"g/{gid}/dev/{did}/{name}"


def token_secret_name(gid, slot):
    """Secret-Store key for a garden's token (slash-free; "." delimiter)."""
    return f"g.{gid}.{slot}"


def render_nav(active_id, view_only):
    """Render the shared nav server-side. Admin (viewer_ok=False) links are OMITTED when
    view_only (the public edge build), so admin destinations never reach viewers. A
    contiguous run of items sharing a non-empty `group` becomes a <details> dropdown
    (label = capitalized group), omitted when the run has no visible items. active_id is
    the full link id, e.g. "nav-history"."""
    out = []
    n = len(NAV)
    i = 0
    while i < n:
        nid, href, label, viewer_ok, group = NAV[i]
        if not group:
            if not (view_only and not viewer_ok):
                full = "nav-" + nid
                cls = ' class="active"' if active_id == full else ""
                out.append(f'  <a href="{href}" id="{full}"{cls}>{label}</a>')
            i += 1
            continue
        run = []
        while i < n and NAV[i][4] == group:
            it = NAV[i]
            if not (view_only and not it[3]):
                run.append(it)
            i += 1
        if not run:
            continue
        gid = "nav-" + group
        gactive = any(active_id == "nav-" + it[0] for it in run)
        gcls = " active" if gactive else ""
        glabel = group[:1].upper() + group[1:]
        out.append(f'  <details class="nav-group{gcls}" id="{gid}"><summary>{glabel}</summary><div class="nav-group-menu">')
        for it in run:
            full = "nav-" + it[0]
            cls = ' class="active"' if active_id == full else ""
            out.append(f'    <a href="{it[1]}" id="{full}"{cls}>{it[2]}</a>')
        out.append("  </div></details>")
    return "\n".join(out)
