#!/usr/bin/env python3
"""contract/gen.py — render contract/spec.toml into the generated cross-language
contract modules (CHARTER: one identity/contract source of truth).

    python contract/gen.py            # write the generated files
    python contract/gen.py --check    # exit 1 if regenerating would change the tree

Outputs (each carries a GENERATED header):
    backend/src/contract_gen.rs    (Rust pub consts + pure fns + a cargo test)
    provision/contract_gen.py      (Python consts + pure fns)
    tests/contract_fixture.json    (expected outputs, for the conformance test)

The generated Rust is PURE (consts + String formatting only) — no host-ABI calls —
so it links under both wasm32 and native `cargo test`.
"""
import json
import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "contract" / "spec.toml"
RS_OUT = ROOT / "backend" / "src" / "contract_gen.rs"
PY_OUT = ROOT / "provision" / "contract_gen.py"
FIX_OUT = ROOT / "tests" / "contract_fixture.json"

NOTE = "GENERATED by contract/gen.py from contract/spec.toml — DO NOT EDIT. Run `make gen`."


def fmt_f32_rust(v):
    """Render a float as a Rust f32 literal: deterministic decimal + explicit _f32 suffix.

    Uses repr() for exact round-trip fidelity, then appends the _f32 type suffix so the
    Rust compiler knows this is f32, not f64. This avoids str() surprises (e.g. scientific
    notation for small values like 1e-05) and prevents silent precision loss if the spec
    value ever changes.
    """
    s = repr(float(v))
    # repr() always includes a decimal point for finite floats, so no extra '.' needed.
    return f"{s}_f32"


def fmt_float_py(v):
    """Render a float as a Python literal: deterministic decimal, no scientific notation.

    Uses repr() for exact round-trip fidelity. repr() of common threshold values like
    0.3 yields '0.3', which is both human-readable and unambiguous as a Python literal.
    """
    return repr(float(v))


def charset_class(tokens):
    """A regex/char-class body from spec tokens, e.g. ['a-z','0-9','-'] -> 'a-z0-9-'."""
    return "".join(tokens)


def charset_rust(tokens):
    """A Rust byte predicate over `b` from spec tokens (ranges 'a-z' + literals)."""
    parts = []
    for t in tokens:
        if len(t) == 3 and t[1] == "-":
            parts.append(f"(b'{t[0]}'..=b'{t[2]}').contains(&b)")
        elif len(t) == 1:
            parts.append(f"b == b'{t}'")
        else:
            raise SystemExit(f"gen: unsupported id_charset token {t!r}")
    return " || ".join(parts)


def nav_items(s):
    """The [[ui.nav]] table as (id, href, label, viewer_ok, group) tuples (group "" if unset)."""
    return [(n["id"], n["href"], n["label"], bool(n["viewer_ok"]), n.get("group", ""))
            for n in s["ui"]["nav"]]


def render_nav_str(nav, active_id, view_only):
    """Reference render of the shared nav. The generated render_nav() in BOTH languages must
    produce this byte-for-byte (pinned by the fixture + cargo gen_tests). A contiguous run of
    items sharing a non-empty `group` is wrapped in a <details> dropdown (label = capitalized
    group); a run with no visible items (e.g. all admin links on the view-only edge) emits
    nothing. The <details> gets class "active" when the active page is inside it."""
    out = []
    n = len(nav)
    i = 0
    while i < n:
        nid, href, label, viewer_ok, group = nav[i]
        if not group:
            if not (view_only and not viewer_ok):
                full = "nav-" + nid
                cls = ' class="active"' if active_id == full else ""
                out.append(f'  <a href="{href}" id="{full}"{cls}>{label}</a>')
            i += 1
            continue
        run = []
        while i < n and nav[i][4] == group:
            it = nav[i]
            if not (view_only and not it[3]):
                run.append(it)
            i += 1
        if not run:
            continue
        gid = "nav-" + group
        gactive = any(active_id == "nav-" + it[0] for it in run)
        gcls = " active" if gactive else ""
        glabel = group[:1].upper() + group[1:]
        out.append(f'  <details class="nav-group{gcls}" id="{gid}"><summary>{glabel}</summary><div class="nav-group-menu">')
        for it in run:
            full = "nav-" + it[0]
            cls = ' class="active"' if active_id == full else ""
            out.append(f'    <a href="{it[1]}" id="{full}"{cls}>{it[2]}</a>')
        out.append("  </div></details>")
    return "\n".join(out)


def nav_literal(nav, true_lit, false_lit):
    """The NAV tuple-array body for a target language (its true/false literals differ)."""
    rows = [
        f'    ({json.dumps(nid)}, {json.dumps(href)}, {json.dumps(label)}, '
        f"{true_lit if viewer_ok else false_lit}, {json.dumps(group)})"
        for nid, href, label, viewer_ok, group in nav
    ]
    return "\n" + ",\n".join(rows) + ",\n"


def sample_outputs(s):
    """Expected fn outputs for representative inputs — the conformance fixture."""
    g, kv, tok = s["identity"], s["kv"], s["token"]
    dg, gp, dev = g["default_garden"], kv["garden_prefix"], kv["dev_segment"]
    pfx, dl = tok["secret_prefix"], tok["secret_delimiter"]
    nav = nav_items(s)
    return {
        "render_nav": {
            # "<active_id>|<view_only>" -> rendered <a> links
            "nav-dashboard|true": render_nav_str(nav, "nav-dashboard", True),
            "nav-history|true": render_nav_str(nav, "nav-history", True),
            "nav-costs|false": render_nav_str(nav, "nav-costs", False),
        },
        "key": {
            f"{dg}|armed": "armed",
            "backyard|armed": f"{gp}/backyard/armed",
        },
        "dev_key": {
            f"{dg}|cam1|latest_event": "latest_event",
            "backyard|cam1|latest_event": f"{gp}/backyard/{dev}/cam1/latest_event",
        },
        "token_secret_name": {
            f"backyard|{tok['slot_current']}": f"{pfx}{dl}backyard{dl}{tok['slot_current']}",
            f"g1|{tok['slot_previous']}": f"{pfx}{dl}g1{dl}{tok['slot_previous']}",
        },
        "is_valid_id": {
            "backyard": True, "g-1": True, "a" * g["id_max_len"]: True,
            "": False, "a" * (g["id_max_len"] + 1): False,
            "g/1": False, "Cafe": False, "a b": False, "g1\n": False,
        },
    }


def render_rust(s):
    g, tok, kv, h = s["identity"], s["token"], s["kv"], s["headers"]
    th, arch, ctl = s["thresholds"], s["archive"], s["control"]
    ui, nav = s["ui"], nav_items(s)
    cmds = ", ".join(f'"{c}"' for c in ctl["commands"])
    T = """// @NOTE@
#![allow(dead_code)]

pub const DEFAULT_GARDEN: &str = "@DG@";
pub const ID_MIN_LEN: usize = @IDMIN@;
pub const ID_MAX_LEN: usize = @IDMAX@;

pub const TOKEN_SLOT_CURRENT: &str = "@SLOTC@";
pub const TOKEN_SLOT_PREVIOUS: &str = "@SLOTP@";

pub const HEADER_GARDEN_ID: &str = "@HGID@";
pub const HEADER_DEVICE_ID: &str = "@HDID@";
pub const HEADER_NODE_ID: &str = "@HNID@";
pub const HEADER_TRACE_ID: &str = "@HTID@";
pub const HEADER_AUTH: &str = "@HAUTH@";
pub const HEADER_CAPTURE_TS: &str = "@HCTS@";
pub const HEADER_CAPTURE_BATCH: &str = "@HCBATCH@";
pub const HEADER_TRIGGER: &str = "@HTRIG@";

pub const NODE_OFFLINE_AFTER_SECS: u64 = @NOFF@;
pub const RAIN_TELEMETRY_FRESH_SECS: u64 = @RAINF@;
pub const MITIGATE_THRESHOLD: f32 = @MITIG@;
pub const SECONDS_PER_DAY: u32 = @SPD@;

pub const CONTROL_COMMANDS: [&str; @NCMD@] = [@CMDS@];

pub const ASSET_VERSION: &str = "@ASSET_VERSION@";

/// The shared nav model (id, href, label, viewer_ok, group), rendered server-side by
/// render_nav() so the edge (view-only) and Pi (admin) tiers can never drift.
pub const NAV: [(&str, &str, &str, bool, &str); @NCNAV@] = [@NAV_RUST@];

/// Tenancy/device/node id validity (charset @CSET@, len @IDMIN@..=@IDMAX@).
pub fn is_valid_id(s: &str) -> bool {
    let n = s.len();
    (ID_MIN_LEN..=ID_MAX_LEN).contains(&n) && s.bytes().all(|b| @CSRUST@)
}

/// garden_state KV key for a garden-level flag (default -> legacy flat key).
pub fn key(gid: &str, name: &str) -> String {
    if gid == DEFAULT_GARDEN {
        name.to_string()
    } else {
        format!("@GP@/{}/{}", gid, name)
    }
}

/// garden_state KV key for a per-device value (default -> legacy global key).
pub fn dev_key(gid: &str, did: &str, name: &str) -> String {
    if gid == DEFAULT_GARDEN {
        name.to_string()
    } else {
        format!("@GP@/{}/@DEV@/{}/{}", gid, did, name)
    }
}

/// Secret-Store key for a garden's token (slash-free; "@DL@" delimiter).
pub fn token_secret_name(gid: &str, slot: &str) -> String {
    format!("@PFX@@DL@{}@DL@{}", gid, slot)
}

/// Render the shared nav server-side. Admin (viewer_ok=false) links are OMITTED when
/// `view_only` (the public edge build), so admin destinations never reach viewers. A
/// contiguous run of items sharing a non-empty `group` becomes a <details> dropdown
/// (label = capitalized group), omitted entirely when the run has no visible items.
/// `active_id` is the full link id, e.g. "nav-history".
pub fn render_nav(active_id: &str, view_only: bool) -> String {
    let mut out: Vec<String> = Vec::new();
    let mut i = 0usize;
    while i < NAV.len() {
        let (nid, href, label, viewer_ok, group) = NAV[i];
        if group.is_empty() {
            if !(view_only && !viewer_ok) {
                let full = format!("nav-{}", nid);
                let cls = if active_id == full.as_str() { " class=\\"active\\"" } else { "" };
                out.push(format!("  <a href=\\"{}\\" id=\\"{}\\"{}>{}</a>", href, full, cls, label));
            }
            i += 1;
            continue;
        }
        let mut run: Vec<(&str, &str, &str, bool, &str)> = Vec::new();
        while i < NAV.len() && NAV[i].4 == group {
            let it = NAV[i];
            if !(view_only && !it.3) {
                run.push(it);
            }
            i += 1;
        }
        if run.is_empty() {
            continue;
        }
        let gid = format!("nav-{}", group);
        let gactive = run.iter().any(|it| active_id == format!("nav-{}", it.0).as_str());
        let gcls = if gactive { " active" } else { "" };
        let mut gchars = group.chars();
        let glabel = match gchars.next() {
            Some(f) => f.to_uppercase().collect::<String>() + gchars.as_str(),
            None => String::new(),
        };
        out.push(format!(
            "  <details class=\\"nav-group{}\\" id=\\"{}\\"><summary>{}</summary><div class=\\"nav-group-menu\\">",
            gcls, gid, glabel
        ));
        for it in &run {
            let full = format!("nav-{}", it.0);
            let cls = if active_id == full.as_str() { " class=\\"active\\"" } else { "" };
            out.push(format!("    <a href=\\"{}\\" id=\\"{}\\"{}>{}</a>", it.1, full, cls, it.2));
        }
        out.push("  </div></details>".to_string());
    }
    out.join("\\n")
}

#[cfg(test)]
mod gen_tests {
    use super::*;
    #[test]
    fn test_generated_contract_matches_spec() {
        assert_eq!(key(DEFAULT_GARDEN, "armed"), "armed");
        assert_eq!(key("backyard", "armed"), "@GP@/backyard/armed");
        assert_eq!(dev_key(DEFAULT_GARDEN, "cam1", "latest_event"), "latest_event");
        assert_eq!(dev_key("backyard", "cam1", "latest_event"), "@GP@/backyard/@DEV@/cam1/latest_event");
        assert_eq!(token_secret_name("backyard", TOKEN_SLOT_CURRENT), "@PFX@@DL@backyard@DL@@SLOTC@");
        assert!(is_valid_id("backyard") && is_valid_id("g-1"));
        assert!(!is_valid_id("") && !is_valid_id("g/1") && !is_valid_id("Cafe"));
        assert!(!token_secret_name("g1", TOKEN_SLOT_CURRENT).contains('/'));
        assert_eq!(NODE_OFFLINE_AFTER_SECS, @NOFF@);
        assert_eq!(RAIN_TELEMETRY_FRESH_SECS, @RAINF@);
        assert_eq!(MITIGATE_THRESHOLD, @MITIG@);
        assert_eq!(SECONDS_PER_DAY, @SPD@);
        assert_eq!(CONTROL_COMMANDS, [@CMDS@]);
        assert_eq!(HEADER_GARDEN_ID, "@HGID@");
        assert_eq!(HEADER_DEVICE_ID, "@HDID@");
        assert_eq!(HEADER_NODE_ID, "@HNID@");
        assert_eq!(HEADER_TRACE_ID, "@HTID@");
        assert_eq!(HEADER_AUTH, "@HAUTH@");
        assert_eq!(HEADER_CAPTURE_TS, "@HCTS@");
        assert_eq!(HEADER_CAPTURE_BATCH, "@HCBATCH@");
        assert_eq!(HEADER_TRIGGER, "@HTRIG@");
        assert_eq!(ASSET_VERSION, "@ASSET_VERSION@");
        assert_eq!(render_nav("nav-costs", false), @NAV_TEST_ADMIN@);
        assert_eq!(render_nav("nav-dashboard", true), @NAV_TEST_VIEW@);
        assert!(!render_nav("nav-dashboard", true).contains("nav-costs"));
    }
}
"""
    repl = {
        "@NOTE@": NOTE, "@DG@": g["default_garden"], "@IDMIN@": g["id_min_len"],
        "@IDMAX@": g["id_max_len"], "@SLOTC@": tok["slot_current"],
        "@SLOTP@": tok["slot_previous"], "@HGID@": h["garden_id"],
        "@HDID@": h["device_id"], "@HNID@": h["node_id"], "@HTID@": h["trace_id"],
        "@HAUTH@": h["auth"], "@HCTS@": h["capture_ts"], "@HCBATCH@": h["capture_batch"],
        "@HTRIG@": h["trigger"],
        "@NOFF@": th["node_offline_after_secs"],
        "@RAINF@": th["rain_telemetry_fresh_secs"],
        "@MITIG@": fmt_f32_rust(th["mitigate_threshold"]),
        "@SPD@": arch["seconds_per_day"], "@NCMD@": len(ctl["commands"]), "@CMDS@": cmds,
        "@CSET@": charset_class(g["id_charset"]), "@CSRUST@": charset_rust(g["id_charset"]),
        "@GP@": kv["garden_prefix"], "@DEV@": kv["dev_segment"],
        "@PFX@": tok["secret_prefix"], "@DL@": tok["secret_delimiter"],
        "@ASSET_VERSION@": ui["asset_version"], "@NCNAV@": len(nav),
        "@NAV_RUST@": nav_literal(nav, "true", "false"),
        "@NAV_TEST_ADMIN@": json.dumps(render_nav_str(nav, "nav-costs", False)),
        "@NAV_TEST_VIEW@": json.dumps(render_nav_str(nav, "nav-dashboard", True)),
    }
    for k, v in repl.items():
        T = T.replace(k, str(v))
    return T


def render_python(s):
    g, tok, kv, h = s["identity"], s["token"], s["kv"], s["headers"]
    th, arch, ctl = s["thresholds"], s["archive"], s["control"]
    ui, nav = s["ui"], nav_items(s)
    cmds = ", ".join(f'"{c}"' for c in ctl["commands"])
    T = '''#!/usr/bin/env python3
# @NOTE@
import re

DEFAULT_GARDEN = "@DG@"
ID_MIN_LEN = @IDMIN@
ID_MAX_LEN = @IDMAX@
_ID_RE = re.compile(r"[@CSET@]{@IDMIN@,@IDMAX@}")

TOKEN_SLOT_CURRENT = "@SLOTC@"
TOKEN_SLOT_PREVIOUS = "@SLOTP@"

HEADER_GARDEN_ID = "@HGID@"
HEADER_DEVICE_ID = "@HDID@"
HEADER_NODE_ID = "@HNID@"
HEADER_TRACE_ID = "@HTID@"
HEADER_AUTH = "@HAUTH@"
HEADER_CAPTURE_TS = "@HCTS@"
HEADER_CAPTURE_BATCH = "@HCBATCH@"
HEADER_TRIGGER = "@HTRIG@"

NODE_OFFLINE_AFTER_SECS = @NOFF@
RAIN_TELEMETRY_FRESH_SECS = @RAINF@
MITIGATE_THRESHOLD = @MITIG@
SECONDS_PER_DAY = @SPD@

CONTROL_COMMANDS = [@CMDS@]

ASSET_VERSION = "@ASSET_VERSION@"

# The shared nav model (id, href, label, viewer_ok, group), rendered server-side by
# render_nav() so the edge (view-only) and Pi (admin) tiers can never drift.
NAV = [@NAV_PY@]


def is_valid_id(s):
    """True iff `s` is a valid tenancy id (charset @CSET@, len @IDMIN@..@IDMAX@)."""
    return isinstance(s, str) and _ID_RE.fullmatch(s) is not None


def key(gid, name):
    """garden_state KV key for a garden-level flag (default -> legacy flat key)."""
    return name if gid == DEFAULT_GARDEN else f"@GP@/{gid}/{name}"


def dev_key(gid, did, name):
    """garden_state KV key for a per-device value (default -> legacy global key)."""
    return name if gid == DEFAULT_GARDEN else f"@GP@/{gid}/@DEV@/{did}/{name}"


def token_secret_name(gid, slot):
    """Secret-Store key for a garden's token (slash-free; "@DL@" delimiter)."""
    return f"@PFX@@DL@{gid}@DL@{slot}"


def render_nav(active_id, view_only):
    """Render the shared nav server-side. Admin (viewer_ok=False) links are OMITTED when
    view_only (the public edge build), so admin destinations never reach viewers. A
    contiguous run of items sharing a non-empty `group` becomes a <details> dropdown
    (label = capitalized group), omitted when the run has no visible items. active_id is
    the full link id, e.g. "nav-history"."""
    out = []
    n = len(NAV)
    i = 0
    while i < n:
        nid, href, label, viewer_ok, group = NAV[i]
        if not group:
            if not (view_only and not viewer_ok):
                full = "nav-" + nid
                cls = ' class="active"' if active_id == full else ""
                out.append(f'  <a href="{href}" id="{full}"{cls}>{label}</a>')
            i += 1
            continue
        run = []
        while i < n and NAV[i][4] == group:
            it = NAV[i]
            if not (view_only and not it[3]):
                run.append(it)
            i += 1
        if not run:
            continue
        gid = "nav-" + group
        gactive = any(active_id == "nav-" + it[0] for it in run)
        gcls = " active" if gactive else ""
        glabel = group[:1].upper() + group[1:]
        out.append(f'  <details class="nav-group{gcls}" id="{gid}"><summary>{glabel}</summary><div class="nav-group-menu">')
        for it in run:
            full = "nav-" + it[0]
            cls = ' class="active"' if active_id == full else ""
            out.append(f'    <a href="{it[1]}" id="{full}"{cls}>{it[2]}</a>')
        out.append("  </div></details>")
    return "\\n".join(out)
'''
    repl = {
        "@NOTE@": NOTE, "@DG@": g["default_garden"], "@IDMIN@": g["id_min_len"],
        "@IDMAX@": g["id_max_len"], "@CSET@": charset_class(g["id_charset"]),
        "@SLOTC@": tok["slot_current"], "@SLOTP@": tok["slot_previous"],
        "@HGID@": h["garden_id"], "@HDID@": h["device_id"], "@HNID@": h["node_id"],
        "@HTID@": h["trace_id"], "@HAUTH@": h["auth"],
        "@HCTS@": h["capture_ts"], "@HCBATCH@": h["capture_batch"],
        "@HTRIG@": h["trigger"],
        "@NOFF@": th["node_offline_after_secs"], "@RAINF@": th["rain_telemetry_fresh_secs"],
        "@MITIG@": fmt_float_py(th["mitigate_threshold"]),
        "@SPD@": arch["seconds_per_day"], "@CMDS@": cmds,
        "@GP@": kv["garden_prefix"], "@DEV@": kv["dev_segment"],
        "@PFX@": tok["secret_prefix"], "@DL@": tok["secret_delimiter"],
        "@ASSET_VERSION@": ui["asset_version"],
        "@NAV_PY@": nav_literal(nav, "True", "False"),
    }
    for k, v in repl.items():
        T = T.replace(k, str(v))
    return T


def render_fixture(s):
    return json.dumps({"note": NOTE, "expected": sample_outputs(s)}, indent=2, sort_keys=True) + "\n"


def validate_spec(s):
    """Fail with a clear message if the spec is structurally invalid.

    Checks: required tables/keys present, nav ids unique, id_min_len <= id_max_len,
    threshold values are numeric. Raises SystemExit with a human-readable message
    instead of letting a KeyError/TypeError surface as a raw traceback.
    """
    errors = []

    # Required top-level tables and their required keys.
    required = {
        "identity": ["default_garden", "id_charset", "id_min_len", "id_max_len"],
        "token": ["secret_prefix", "secret_delimiter", "slot_current", "slot_previous"],
        "kv": ["garden_prefix", "dev_segment"],
        "headers": ["garden_id", "device_id", "node_id", "trace_id", "auth",
                    "capture_ts", "capture_batch", "trigger"],
        "thresholds": ["node_offline_after_secs", "rain_telemetry_fresh_secs",
                       "mitigate_threshold"],
        "archive": ["seconds_per_day"],
        "control": ["commands"],
        "ui": ["asset_version", "nav"],
    }
    for table, keys in required.items():
        if table not in s:
            errors.append(f"missing required table [{table}]")
            continue
        for key in keys:
            if key not in s[table]:
                errors.append(f"missing required key [{table}].{key}")

    if errors:
        raise SystemExit("gen: spec validation failed:\n" + "\n".join(f"  - {e}" for e in errors))

    g = s["identity"]
    th = s["thresholds"]

    # id length ordering
    lo, hi = g["id_min_len"], g["id_max_len"]
    if not isinstance(lo, int) or not isinstance(hi, int):
        errors.append("identity.id_min_len and id_max_len must be integers")
    elif lo > hi:
        errors.append(
            f"identity.id_min_len ({lo}) must be <= id_max_len ({hi})"
        )

    # threshold values must be numeric
    for name in ("node_offline_after_secs", "rain_telemetry_fresh_secs",
                 "mitigate_threshold"):
        v = th.get(name)
        if not isinstance(v, (int, float)):
            errors.append(f"thresholds.{name} must be numeric, got {type(v).__name__}")

    # nav ids must be unique
    nav = s["ui"].get("nav", [])
    seen_ids = set()
    for item in nav:
        nid = item.get("id")
        if nid is None:
            errors.append("a [[ui.nav]] entry is missing the 'id' key")
        elif nid in seen_ids:
            errors.append(f"duplicate nav id: {nid!r}")
        else:
            seen_ids.add(nid)

    if errors:
        raise SystemExit("gen: spec validation failed:\n" + "\n".join(f"  - {e}" for e in errors))


def main():
    spec = tomllib.loads(SPEC.read_text())
    validate_spec(spec)
    targets = {RS_OUT: render_rust(spec), PY_OUT: render_python(spec), FIX_OUT: render_fixture(spec)}
    check = "--check" in sys.argv[1:]
    drift = []
    for path, content in targets.items():
        current = path.read_text() if path.exists() else None
        if current != content:
            drift.append(path)
            if not check:
                path.write_text(content)
    rel = [str(p.relative_to(ROOT)) for p in drift]
    if check:
        if drift:
            print("gen-check: generated files are STALE — run `make gen`:")
            for r in rel:
                print(f"  - {r}")
            sys.exit(1)
        print("gen-check: generated files match contract/spec.toml ✓")
    else:
        print("gen: wrote " + (", ".join(rel) if rel else "nothing (already up to date)"))


if __name__ == "__main__":
    main()
