// GENERATED by contract/gen.py from contract/spec.toml — DO NOT EDIT. Run `make gen`.
#![allow(dead_code)]

pub const DEFAULT_GARDEN: &str = "default";
pub const ID_MIN_LEN: usize = 1;
pub const ID_MAX_LEN: usize = 64;

pub const TOKEN_SLOT_CURRENT: &str = "token_current";
pub const TOKEN_SLOT_PREVIOUS: &str = "token_previous";

pub const HEADER_GARDEN_ID: &str = "X-Garden-Id";
pub const HEADER_DEVICE_ID: &str = "X-Device-Id";
pub const HEADER_NODE_ID: &str = "X-Node-Id";
pub const HEADER_TRACE_ID: &str = "X-Garden-Trace-Id";
pub const HEADER_AUTH: &str = "X-Garden-Auth";
pub const HEADER_CAPTURE_TS: &str = "X-Capture-Ts";
pub const HEADER_CAPTURE_BATCH: &str = "X-Capture-Batch";
pub const HEADER_TRIGGER: &str = "X-Trigger";

pub const NODE_OFFLINE_AFTER_SECS: u64 = 150;
pub const RAIN_TELEMETRY_FRESH_SECS: u64 = 600;
pub const MITIGATE_THRESHOLD: f32 = 0.3_f32;
pub const SECONDS_PER_DAY: u32 = 86400;

pub const CONTROL_COMMANDS: [&str; 7] = ["off", "monitor", "active", "stop", "resume", "arm", "disarm"];

pub const ASSET_VERSION: &str = "31";

/// The shared nav model (id, href, label, viewer_ok, group), rendered server-side by
/// render_nav() so the edge (view-only) and Pi (admin) tiers can never drift.
pub const NAV: [(&str, &str, &str, bool, &str); 10] = [
    ("dashboard", "/", "Dashboard", true, ""),
    ("history", "/history", "History", true, ""),
    ("timelapse", "/timelapse", "Timelapse", true, ""),
    ("alarms", "/alarms", "Alarms", true, ""),
    ("devices", "/devices", "Gadgets", false, "admin"),
    ("settings", "/settings", "Settings", false, "admin"),
    ("costs", "/costs", "Costs", false, "admin"),
    ("logs", "/logs", "Logs", false, "admin"),
    ("storage", "/storage", "Storage", false, "admin"),
    ("help", "/help", "Help", true, ""),
];

/// Tenancy/device/node id validity (charset a-z0-9-, len 1..=64).
pub fn is_valid_id(s: &str) -> bool {
    let n = s.len();
    (ID_MIN_LEN..=ID_MAX_LEN).contains(&n) && s.bytes().all(|b| (b'a'..=b'z').contains(&b) || (b'0'..=b'9').contains(&b) || b == b'-')
}

/// garden_state KV key for a garden-level flag (default -> legacy flat key).
pub fn key(gid: &str, name: &str) -> String {
    if gid == DEFAULT_GARDEN {
        name.to_string()
    } else {
        format!("g/{}/{}", gid, name)
    }
}

/// garden_state KV key for a per-device value (default -> legacy global key).
pub fn dev_key(gid: &str, did: &str, name: &str) -> String {
    if gid == DEFAULT_GARDEN {
        name.to_string()
    } else {
        format!("g/{}/dev/{}/{}", gid, did, name)
    }
}

/// Secret-Store key for a garden's token (slash-free; "." delimiter).
pub fn token_secret_name(gid: &str, slot: &str) -> String {
    format!("g.{}.{}", gid, slot)
}

/// Render the shared nav server-side. Admin (viewer_ok=false) links are OMITTED when
/// `view_only` (the public edge build), so admin destinations never reach viewers. A
/// contiguous run of items sharing a non-empty `group` becomes a <details> dropdown
/// (label = capitalized group), omitted entirely when the run has no visible items.
/// `active_id` is the full link id, e.g. "nav-history".
pub fn render_nav(active_id: &str, view_only: bool) -> String {
    let mut out: Vec<String> = Vec::new();
    let mut i = 0usize;
    while i < NAV.len() {
        let (nid, href, label, viewer_ok, group) = NAV[i];
        if group.is_empty() {
            if !(view_only && !viewer_ok) {
                let full = format!("nav-{}", nid);
                let cls = if active_id == full.as_str() { " class=\"active\"" } else { "" };
                out.push(format!("  <a href=\"{}\" id=\"{}\"{}>{}</a>", href, full, cls, label));
            }
            i += 1;
            continue;
        }
        let mut run: Vec<(&str, &str, &str, bool, &str)> = Vec::new();
        while i < NAV.len() && NAV[i].4 == group {
            let it = NAV[i];
            if !(view_only && !it.3) {
                run.push(it);
            }
            i += 1;
        }
        if run.is_empty() {
            continue;
        }
        let gid = format!("nav-{}", group);
        let gactive = run.iter().any(|it| active_id == format!("nav-{}", it.0).as_str());
        let gcls = if gactive { " active" } else { "" };
        let mut gchars = group.chars();
        let glabel = match gchars.next() {
            Some(f) => f.to_uppercase().collect::<String>() + gchars.as_str(),
            None => String::new(),
        };
        out.push(format!(
            "  <details class=\"nav-group{}\" id=\"{}\"><summary>{}</summary><div class=\"nav-group-menu\">",
            gcls, gid, glabel
        ));
        for it in &run {
            let full = format!("nav-{}", it.0);
            let cls = if active_id == full.as_str() { " class=\"active\"" } else { "" };
            out.push(format!("    <a href=\"{}\" id=\"{}\"{}>{}</a>", it.1, full, cls, it.2));
        }
        out.push("  </div></details>".to_string());
    }
    out.join("\n")
}

#[cfg(test)]
mod gen_tests {
    use super::*;
    #[test]
    fn test_generated_contract_matches_spec() {
        assert_eq!(key(DEFAULT_GARDEN, "armed"), "armed");
        assert_eq!(key("backyard", "armed"), "g/backyard/armed");
        assert_eq!(dev_key(DEFAULT_GARDEN, "cam1", "latest_event"), "latest_event");
        assert_eq!(dev_key("backyard", "cam1", "latest_event"), "g/backyard/dev/cam1/latest_event");
        assert_eq!(token_secret_name("backyard", TOKEN_SLOT_CURRENT), "g.backyard.token_current");
        assert!(is_valid_id("backyard") && is_valid_id("g-1"));
        assert!(!is_valid_id("") && !is_valid_id("g/1") && !is_valid_id("Cafe"));
        assert!(!token_secret_name("g1", TOKEN_SLOT_CURRENT).contains('/'));
        assert_eq!(NODE_OFFLINE_AFTER_SECS, 150);
        assert_eq!(RAIN_TELEMETRY_FRESH_SECS, 600);
        assert_eq!(MITIGATE_THRESHOLD, 0.3_f32);
        assert_eq!(SECONDS_PER_DAY, 86400);
        assert_eq!(CONTROL_COMMANDS, ["off", "monitor", "active", "stop", "resume", "arm", "disarm"]);
        assert_eq!(HEADER_GARDEN_ID, "X-Garden-Id");
        assert_eq!(HEADER_DEVICE_ID, "X-Device-Id");
        assert_eq!(HEADER_NODE_ID, "X-Node-Id");
        assert_eq!(HEADER_TRACE_ID, "X-Garden-Trace-Id");
        assert_eq!(HEADER_AUTH, "X-Garden-Auth");
        assert_eq!(HEADER_CAPTURE_TS, "X-Capture-Ts");
        assert_eq!(HEADER_CAPTURE_BATCH, "X-Capture-Batch");
        assert_eq!(HEADER_TRIGGER, "X-Trigger");
        assert_eq!(ASSET_VERSION, "31");
        assert_eq!(render_nav("nav-costs", false), "  <a href=\"/\" id=\"nav-dashboard\">Dashboard</a>\n  <a href=\"/history\" id=\"nav-history\">History</a>\n  <a href=\"/timelapse\" id=\"nav-timelapse\">Timelapse</a>\n  <a href=\"/alarms\" id=\"nav-alarms\">Alarms</a>\n  <details class=\"nav-group active\" id=\"nav-admin\"><summary>Admin</summary><div class=\"nav-group-menu\">\n    <a href=\"/devices\" id=\"nav-devices\">Gadgets</a>\n    <a href=\"/settings\" id=\"nav-settings\">Settings</a>\n    <a href=\"/costs\" id=\"nav-costs\" class=\"active\">Costs</a>\n    <a href=\"/logs\" id=\"nav-logs\">Logs</a>\n    <a href=\"/storage\" id=\"nav-storage\">Storage</a>\n  </div></details>\n  <a href=\"/help\" id=\"nav-help\">Help</a>");
        assert_eq!(render_nav("nav-dashboard", true), "  <a href=\"/\" id=\"nav-dashboard\" class=\"active\">Dashboard</a>\n  <a href=\"/history\" id=\"nav-history\">History</a>\n  <a href=\"/timelapse\" id=\"nav-timelapse\">Timelapse</a>\n  <a href=\"/alarms\" id=\"nav-alarms\">Alarms</a>\n  <a href=\"/help\" id=\"nav-help\">Help</a>");
        assert!(!render_nav("nav-dashboard", true).contains("nav-costs"));
    }
}
